uploads = []
generated = []

[[outputs]]
id = "7-ciVXaGeBvl6tkM3wXQm"
uri = "file://docs/PRD.md"
type = "text"
title = "FamJam PRD"

[[outputs]]
id = "8eP8JZV1UoFErjtNAhTR_"
uri = "file://docs/RECREATION_GUIDE.md"
type = "text"
title = "FamJam Recreation Guide"
